export const FIREBASE_AUTHENTICATION_ERRORS = [
	{ id: "auth/claims-too-large", message: "An error occurred. Code : 401" },
	{ id: "auth/id-token-expired", message: "An error occurred. Code : 402" },
	{ id: "auth/id-token-revoked", message: "An error occurred. Code : 403" },
	{ id: "auth/insufficient-permission", message: "An error occurred. Code : 404" },
	{ id: "auth/internal-error", message: "An error occurred. Code : 405" },
	{ id: "auth/invalid-argument", message: "An error occurred. Code : 406" },
	{ id: "auth/invalid-claims", message: "An error occurred. Code : 407" },
	{ id: "auth/invalid-continue-uri", message: "An error occurred. Code : 408" },
	{ id: "auth/invalid-creation-time", message: "An error occurred. Code : 409" },
	{ id: "auth/invalid-credential", message: "An error occurred. Code : 410" },
	{ id: "auth/invalid-disabled-field", message: "An error occurred. Code : 411" },
	{ id: "auth/invalid-display-name", message: "An error occurred. Code : 412" },
	{ id: "auth/invalid-dynamic-link-domain", message: "An error occurred. Code : 413" },
	{ id: "auth/invalid-hash-algorithm", message: "An error occurred. Code : 414" },
	{ id: "auth/invalid-hash-block-size", message: "An error occurred. Code : 415" },
	{ id: "auth/invalid-hash-derived-key-length", message: "An error occurred. Code : 416" },
	{ id: "auth/invalid-hash-key", message: "An error occurred. Code : 417" },
	{ id: "auth/invalid-hash-memory-cost", message: "An error occurred. Code : 418" },
	{ id: "auth/invalid-hash-parallelization", message: "An error occurred. Code : 419" },
	{ id: "auth/invalid-hash-rounds", message: "An error occurred. Code : 420" },
	{ id: "auth/invalid-hash-salt-separator", message: "An error occurred. Code : 421" },
	{ id: "auth/invalid-id-token", message: "An error occurred. Code : 422" },
	{ id: "auth/invalid-last-sign-in-time", message: "An error occurred. Code : 423" },
	{ id: "auth/invalid-page-token", message: "An error occurred. Code : 424" },
	{ id: "auth/invalid-password-hash", message: "An error occurred. Code : 425" },
	{ id: "auth/invalid-password-salt", message: "An error occurred. Code : 426" },
	{ id: "auth/invalid-phone-number", message: "An error occurred. Code : 427" },
	{ id: "auth/invalid-photo-url", message: "An error occurred. Code : 428" },
	{ id: "auth/invalid-provider-data", message: "An error occurred. Code : 429" },
	{ id: "auth/invalid-provider-id", message: "An error occurred. Code : 430" },
	{ id: "auth/invalid-oauth-responsetype", message: "An error occurred. Code : 431" },
	{ id: "auth/invalid-session-cookie-duration", message: "An error occurred. Code : 432" },
	{ id: "auth/invalid-uid", message: "An error occurred. Code : 433" },
	{ id: "auth/invalid-user-import", message: "An error occurred. Code : 434" },
	{ id: "auth/maximum-user-count-exceeded", message: "An error occurred. Code : 435" },
	{ id: "auth/missing-android-pkg-name", message: "An error occurred. Code : 436" },
	{ id: "auth/missing-continue-uri", message: "An error occurred. Code : 437" },
	{ id: "auth/missing-hash-algorithm", message: "An error occurred. Code : 438" },
	{ id: "auth/missing-ios-bundle-id", message: "An error occurred. Code : 439" },
	{ id: "auth/missing-uid", message: "An error occurred. Code : 440" },
	{ id: "auth/missing-oauth-client-secret", message: "An error occurred. Code : 441" },
	{ id: "auth/operation-not-allowed", message: "An error occurred. Code : 442" },
	{ id: "auth/phone-number-already-exists", message: "An error occurred. Code : 443" },
	{ id: "auth/project-not-found", message: "An error occurred. Code : 444" },
	{ id: "auth/reserved-claims", message: "An error occurred. Code : 445" },
	{ id: "auth/session-cookie-expired", message: "An error occurred. Code : 446" },
	{ id: "auth/session-cookie-revoked", message: "An error occurred. Code : 447" },
	{ id: "auth/uid-already-exists", message: "An error occurred. Code : 448" },
	{ id: "auth/unauthorized-continue-uri", message: "An error occurred. Code : 449" },

	{ id: "auth/user-not-found", message: "User not found." },
	{ id: "auth/too-many-requests", message: "Too many attemps, try again later." },
	{ id: "auth/invalid-password", message: "Wrong email or password." },
	{ id: "auth/wrong-password", message: "Wrong email or password." },
	{ id: "auth/email-already-exists", message: "Email is already used." },
	{ id: "auth/invalid-email", message: "Wrong email or password." },
	{ id: "auth/invalid-email-verified", message: "Invalid email verified" },
]
  
